// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class DetailPesanan
{
    public int DetailPesananId { get; set; }

    public int PesananId { get; set; }

    public int MenuId { get; set; }

    public int Jumlah { get; set; }

    public double HargaSatuan { get; set; }

    public string Catatan { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Pesanan Pesanan { get; set; }
}