// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class LogAktivita
{
    public int LogId { get; set; }

    public int PegawaiId { get; set; }

    public string Aktivitas { get; set; }

    public DateTime TanggalAktivitas { get; set; }

    public string JenisAktivitas { get; set; }

    public string Deskripsi { get; set; }

    public int? BerhasilKah { get; set; }

    public virtual Pegawai Pegawai { get; set; }
}