// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Meja
{
    public int MejaId { get; set; }

    public string NomorMeja { get; set; }

    public int Kapasitas { get; set; }

    public string StatusMeja { get; set; }

    public int AktifKah { get; set; }

    public virtual ICollection<Pesanan> Pesanans { get; set; } = new List<Pesanan>();

    public virtual ICollection<Reservasi> Reservasis { get; set; } = new List<Reservasi>();
}