// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class MenuBahan
{
    public int MenuBahanId { get; set; }

    public int MenuId { get; set; }

    public int BahanId { get; set; }

    public double JumlahDibutuhkan { get; set; }

    public virtual StokBahan Bahan { get; set; }

    public virtual Menu Menu { get; set; }
}