// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Menu
{
    public int MenuId { get; set; }

    public string NamaMenu { get; set; }

    public string Kategori { get; set; }

    public double Harga { get; set; }

    public int TersediaKah { get; set; }

    public int StokTersedia { get; set; }

    public string Deskripsi { get; set; }

    public string GambarMenu { get; set; }

    public int WaktuPembuatan { get; set; }

    public DateOnly TanggalDitambahkan { get; set; }

    public virtual ICollection<DetailPesanan> DetailPesanans { get; set; } = new List<DetailPesanan>();

    public virtual ICollection<MenuBahan> MenuBahans { get; set; } = new List<MenuBahan>();
}