// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Pegawai
{
    public int PegawaiId { get; set; }

    public string NamaPegawai { get; set; }

    public string NamaPengguna { get; set; }

    public string KataSandi { get; set; }

    public int AktifKah { get; set; }

    public string PeranPegawai { get; set; }

    public DateOnly TanggalMulai { get; set; }

    public virtual ICollection<LogAktivita> LogAktivita { get; set; } = new List<LogAktivita>();

    public virtual ICollection<Pembayaran> Pembayarans { get; set; } = new List<Pembayaran>();

    public virtual ICollection<Pesanan> Pesanans { get; set; } = new List<Pesanan>();

    public virtual ICollection<Reservasi> Reservasis { get; set; } = new List<Reservasi>();
}