// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Pembayaran
{
    public int PembayaranId { get; set; }

    public int PesananId { get; set; }

    public int PegawaiId { get; set; }

    public double JumlahBayar { get; set; }

    public string MetodeBayar { get; set; }

    public string NotaNomor { get; set; }

    public string TanggalBayar { get; set; }

    public int BerhasilKah { get; set; }

    public virtual Pegawai Pegawai { get; set; }

    public virtual Pesanan Pesanan { get; set; }
}