// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Pesanan
{
    public int PesananId { get; set; }

    public int MejaId { get; set; }

    public int PegawaiId { get; set; }

    public string TanggalPesanan { get; set; }

    public string StatusPesanan { get; set; }

    public double TotalHarga { get; set; }

    public string WaktuSelesai { get; set; }

    public int DibayarKah { get; set; }

    public virtual ICollection<DetailPesanan> DetailPesanans { get; set; } = new List<DetailPesanan>();

    public virtual Meja Meja { get; set; }

    public virtual Pegawai Pegawai { get; set; }

    public virtual ICollection<Pembayaran> Pembayarans { get; set; } = new List<Pembayaran>();

    public virtual ICollection<Ulasan> Ulasans { get; set; } = new List<Ulasan>();
}