// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Reservasi
{
    public int ReservasiId { get; set; }

    public int MejaId { get; set; }

    public int PegawaiId { get; set; }

    public string NamaPelanggan { get; set; }

    public int JumlahPelanggan { get; set; }

    public DateOnly TanggalReservasi { get; set; }

    public TimeSpan WaktuReservasi { get; set; }

    public string StatusReservasi { get; set; }

    public int AktifKah { get; set; }

    public virtual Meja Meja { get; set; }

    public virtual Pegawai Pegawai { get; set; }
}