// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class StokBahan
{
    public int BahanId { get; set; }

    public string NamaBahan { get; set; }

    public double JumlahStok { get; set; }

    public string Satuan { get; set; }

    public int TersediaKah { get; set; }

    public DateTime TanggalDiperbarui { get; set; }

    public virtual ICollection<MenuBahan> MenuBahans { get; set; } = new List<MenuBahan>();
}