// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestoUnikom.Data.Models;

public partial class Ulasan
{
    public int UlasanId { get; set; }

    public int PesananId { get; set; }

    public int Rating { get; set; }

    public string Komentar { get; set; }

    public string TanggalUlasan { get; set; }

    public int AktifKah { get; set; }

    public virtual Pesanan Pesanan { get; set; }
}